# Utiliser une image de base avec Python
FROM python:3.10-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers nécessaires dans le conteneur
COPY ./src/server1.py /app/
COPY ./requirements.txt /app/

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port sur lequel le serveur sera en cours d'exécution
EXPOSE 5000

# Commande pour démarrer le serveur
CMD ["python", "server1.py"]
